Compile with G++ 7.1
A patch by Olivier Roussel:

This version of G++ warns against using * in a Boolean
context (which makes sense) and gives the following message.

    error: '*' in boolean context, suggest '&&' instead
    !(VarY.min() * VarZ.min()));
     ~~~~~~~~~~~~^~~~~~~~~~~~~